export const PASSWORD_THROTTLER_NAME = "password";
export const PASSWORD_THROTTLE_LIMIT = 1;
export const PASSWORD_THROTTLE_TTL_MS = 2 * 60 * 1000;

export const PASSWORD_THROTTLER = {
  name: PASSWORD_THROTTLER_NAME,
  limit: PASSWORD_THROTTLE_LIMIT,
  ttl: PASSWORD_THROTTLE_TTL_MS,
};

export const PASSWORD_THROTTLE = {
  [PASSWORD_THROTTLER_NAME]: {
    limit: PASSWORD_THROTTLE_LIMIT,
    ttl: PASSWORD_THROTTLE_TTL_MS,
  },
};
